### ISSUE TITLE
Multi-account & IB account ID migration

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#6]
Hi,

Wanted to ask a few things in regards of recent migration of accounts opened in UK to EU offices:

1. It looks like account IDs have changed this year from `U30XXXXX` to `U70XXXXX` (or similar depending on the office where IB migrated you). Does it mean that we have to tweak the `accountID` in XMLs for the past years for script to be able to connect the dots (i.e positions opened in year 2020 and closed in year 2021). This is more of a problem of the next year because I think they flipped account IDs on January 5.
2. Does the script respect account ID? I have multiple sub-accounts and I don't mind reporting them in one go. Would you suggest maintaining XML files per account and then just file multiple reports via e-davki or file one consolidated report? I am asking because I am not sure if e-davki will let one file multiple reports within the same year, because who knows, the system is often mysterious.

Your script saves my life this year too, I wish I could gittip you or something. Thanks for all the work!

p.s.: I really appreciate that you've added support for futures 👍 

Best regards,
Andrej

**Comment by jamsix** [comment]
Andrej,

1. The script doesn't care about the IB account ID and relies on you providing the right IB XML inputs. That means that all you need to do is create exports from both your accounts and the script will connect the dots. For example I had two IB accounts in 2020 and did some position transfers between the two so I simply include both:
`python ib_edavki.py FURS-2017-OldAcc.xml FURS-2018-OldAcc.xml FURS-2019-OldAcc.xml FURS-2020-OldAcc.xml FURS-2020-NewAcc.xml`

2. Because eDavki really only allows you one report per asset type, the right way to report it is to merge trades from all your accounts/brokers into a single eDavki form. This can potentially save you some trouble as well, because FURS requires strict FIFO order of trades regardless of your broker or account used. For example:
- You buy 100 shares of `AAPL` on account/broker #1 in Jan
- You buy 50 shares of `AAPL` on account/broker #2 in Feb
- You sell 50 shares of `AAPL` on account/broker #2 in Mar
- You keep 100 shares of `AAPL` on account/brokder #1 into the next year
The actual trade you need to report following the FIFO rule is buy 50 in Jan and sell 50 in Mar and the only way the script can do this right is when you provide all the data in a single run. Ideally you would pipe the data from all your brokers into the script, alas it only supports IB for now.

Happy that the script is useful :) I'll think about the gittip ;)

Cheers

**Comment by pronebird** [comment]
That makes sense. Thanks for getting back to me that quickly.

**Comment by jamsix** [comment]
@pronebird with https://github.com/jamsix/ib-edavki/pull/22 you can now use a single flex statement for both accounts.

**Comment by pronebird** [comment]
@jamsix do you mean that I can select multiple accounts on IB when exporting a flex report? I had impression that IB never exported data for multiple accounts.

**Comment by jamsix** [comment]
With this year's IB migration, most IB users got two Accounts under their single login username and you can select both when creating reports:
![image](https://user-images.githubusercontent.com/4974831/108825303-23862b00-75c3-11eb-84e8-a5e3db74f415.png)

However, if you have two login usernames (say one on IB, one on one of their white-labels, such as CapTrader, OptimTrader, ...), these are still separated.
