### ISSUE TITLE
IBKR Stock Yield Enhancement Program gains

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#7]
Hey,

Do you report stock yield gains somehow? I am not really sure how to report those. I could probably export XML and see inside if there is some information on that.

Cheers,
Andrej

**Comment by jamsix** [comment]
The script doesn't do that yet. If you can help me out with what exactly this gains fall under (interests?), I'm happy to add it.

**Comment by pronebird** [comment]
Falls under "Interest Accrued" to my understanding. I can try exporting XML and see how it looks there. The reports that IBKR generates are fairly verbose so it's difficult to read them.

**Comment by jamsix** [comment]
Alright, do you have any idea how is this reported to FURS? As interests in `Doh-Obr`?

**Comment by pronebird** [comment]
@jamsix I am gonna have to read on that. But for now this is just an idea. I think those interest payments have to be reported even if they are so small, although I am thinking to enable stock yield program for my main account and see how much I can squeeze. (Holding some heavily shorted stocks)

**Comment by ddbk** [comment]
In my understanding they need to be reported to FURS on the DOHKAP 1 form (https://edavki.durs.si/EdavkiPortal/OpenPortal/CommonPages/Opdynp/PageD.aspx?category=odmera_dohodnine_od_drugih_obresti). Not sure about the reporting code (šifra) though, so I might need to look a bit more into it.

**Comment by ddbk** [comment]
I just received written confirmation from FURS that Stock Yield Enhancement Program gains should indeed be reported in DOHKAP-1 or Doh-Obr forms (both are essentially the same) and that reporting code ("šifra vrste obresti") is not that important since it doesn't affect taxation. Their advice is to choose the one most most closely resembling this type of interest (their suggestion is code no. 2 -- although in my opinion no. 8 is maybe more appropriate?).

These are all the codes:

```
Šifra | Naziv
1 | Obresti od posojil
2 | Obresti od dolžniško vrednostnih papirjev, vključno z zamenljivimi dolžniškimi vrednostnimi papirji
3 | Obresti na denarne depozite pri bankah in hranilnicah
4 | Obresti od podobnih finančnih terjatev do dolžnikov
5 | Dohodek iz oddajanja v finančni najem
6 | Dohodek iz življenjskega zavarovanja
7 | Dohodek, dosežen na podlagi delitve prihodkov vzajemnega sklada v obliki obresti
8 | Nadomestila, diskonti, bonusi, premije, ki se obdavčujejo kot obresti
9 | Dohodek iz dodatnega pokojninskega zavarovanja, sklenjenega po pokojninskem načrtu, ki ni vpisan v poseben register, in dohodek iz prostovoljnega zavarovanja
```

**Comment by ddbk** [comment]
I prepared a pull request for this feature.

For clarification since there was some discussion above about what data to use for generating the report:
Taking interest accruals is not the correct way to report this since FURS only cares about the actual payments. Gains are paid by IB once per month (this is report date for tax purposes) and are reported as cash transaction with type `Broker Interest Received`. This is also relevant since we need to report IB affiliate as the Interest payer.
